name: Validate PyPy e2e
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 30 3 * * *

jobs:
  setup-pypy:
    name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04, ubuntu-latest]
        pypy:
        - 'pypy2.7-v7.3.9'
        - 'pypy3.7-v7.3.9'
        - 'pypy3.8-v7.3.9'
        - 'pypy3.9-v7.3.9'
        - 'pypy2.7-nightly'
        - 'pypy3.7-nightly'
        - 'pypy3.8-nightly'
        - 'pypy3.9-nightly'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-python ${{ matrix.pypy }}
        uses: ./
        with:
          python-version: ${{ matrix.pypy }}

      - name: PyPy and Python version
        run: python --version

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

      - name: Assert PyPy is running
        run: |
          import platform
          assert platform.python_implementation().lower() == "pypy"
        shell: python

      - name: Assert expected binaries (or symlinks) are present
        run: |
          EXECUTABLE=${{ matrix.pypy }}
          EXECUTABLE=${EXECUTABLE/pypy-/pypy}  # remove the first '-' in "pypy-X.Y" -> "pypyX.Y" to match executable name
          EXECUTABLE=${EXECUTABLE%%-*}  # remove any -* suffixe
          echo "Testing ${EXECUTABLE}"
          ${EXECUTABLE} --version
          echo "Testing ${EXECUTABLE/pypy/python}"
          ${EXECUTABLE/pypy/python} --version
          EXECUTABLE=${EXECUTABLE:0:5}
          echo "Testing ${EXECUTABLE}"
          ${EXECUTABLE} --version
          echo "Testing ${EXECUTABLE/pypy/python}"
          ${EXECUTABLE/pypy/python} --version
          echo "Testing pypy"
          pypy --version
        shell: bash
